version: '3.8'

services:
  backend-1:
    container_name: calendar-backend-1
    image: ghcr.io/tanaythatte17/calendar-backend:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3001:3000"
    networks:
      - calendar-net

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --interval 30
