version: '3.8'

services:
  backend-1:
    container_name: calendar-backend-1
    image: tanaythatte17/calendar-backend:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3001:3000"
    networks:
      - calendar-net

  frontend:
    container_name: calendar-frontend
    build:
      context: ./frontend  # Build from local folder or use image from Docker Hub if it already contains Nginx
    restart: always
    ports:
      - "8080:80"          # Host port 8080 -> container port 80
    networks:
      - calendar-net

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --interval 300
      --cleanup
      calendar-backend-1
      calendar-frontend

networks:
  calendar-net:
    driver: bridge